services:
  
  code-editor-webapp:
    build: ./code-editor-webapp
    restart: always
    depends_on:
      - code-sync-service
      - code-exec-service
    ports:
      - 8888:3000
  
  code-sync-service:
    build: ./code-sync-service
    restart: always
    ports:
      - 8889:4000
  
  code-exec-service:
    build: ./code-exec-service
    restart: always
    depends_on:
      - mongodb
      - redisdb
    ports:
      - 8890:5000
  
  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - mongodb:/data/db
  
  redisdb:
    image: redis:7
    restart: always

volumes:
  mongodb: {}