version: '3.9'

services:
  
  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - mongodb:/data/db
  
  redisdb:
    image: redis:7
    restart: always
  
  code-exec-service:
    build: .
    ports:
      - 3020:5000
    depends_on:
      - mongodb
      - redisdb

volumes:
  mongodb: {}