services:

  code-exec-service:
    build: .
    restart: always
    ports:
      - 8080:5000
    depends_on:
      - redisdb
  
  redisdb:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379